apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mongodb
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
  type: {{ .Values.service.type }}
