apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: banti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database | quote }}
