apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: banti
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
