apiVersion: v1
kind: Service
metadata:
  name: usernode-js
  namespace: banti
spec:
  selector:
    app: userprofile
  ports:
    - port: {{ .Values.userprofile.port }}
      targetPort: {{ .Values.userprofile.port }}
  type: ClusterIP
